jupyterhub:
  debug:
    enabled: true

  hub:
    db:
      type: sqlite-memory
    networkPolicy:
      enabled: false
    image:
      name: lsstsqre/nublado2
      tag: dev
      pullPolicy: Never

  singleuser:
    storage:
      type: none
    initContainers:
      - name: junecleaver
        image: lsstsqre/inittmpdirhome:latest
        volumeMounts:
        - name: home
          mountPath: /home
        envFrom:
        - configMapRef:
            name: lab-environment

  ingress:
    hosts: ["minikube.lsst.codes"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"

config:
  base_url: "https://minikube.lsst.codes"
  images_url: "http://cachemachine.cachemachine.svc.cluster.local/cachemachine/jupyter/available"
  volumes:
    - name: home
      emptyDir: {}
  volume_mounts:
    - name: home
      mountPath: /home

vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
gafaelfawr_secret_path: "secret/k8s_operator/minikube.lsst.codes/gafaelfawr"
